### ISSUE TITLE
Server side rendering

### ISSUE THREAD

**Issue by robations** [astoilkov/use-local-storage-state#1]
It would be useful if the hook could test for the presence of the window object to enable server-side rendering more easily. For example:

i. test for window object
ii. if doesn't exist, return `defaultValue`

Any thoughts? This might still leave a potential issue with `updateValue`?

**Comment by astoilkov** [comment]
This can be easily done outside the library with a parent hook. I wrote the code below. If this issue gets enough votes I will add this approach to the readme:

```typescript
import useLocalStorageState from 'use-local-storage-state'

export default function useIsomorphicLocalStorageState<T>(
  key: string,
  defaultValue?: T,
): ReturnType<typeof useLocalStorageState> {
  if (typeof window === 'undefined') {
    return [defaultValue, () => {
      throw new Error('Setting a value is not supported inside server-side rendered apps')
    }]
  }

  return useLocalStorageState(key, defaultValue)
}
```

Generally, if I can I want to avoid adding logic than can go outside of the library. Do you agree?

**Comment by robations** [comment]
> I want to avoid adding logic than can go outside of the library. Do you agree?

Yes, and thanks, sounds like a good principle 👍

With your example code I had a problem with typing the return value, the value from the hook was inferred as `unknown`. I ended up copying the return type into my hook and it worked (TS 3.8.3). I wonder if you need to specify the `types` field [in package.json](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html)?

One other idea for allowing extension — it might be useful to allow injecting the localStorage object into the hook (e.g. as an optional third parameter). This would allow another way to extend for SSR or for testing (with a mock localStorage), and would also allow people to inject sessionStorage, which has the same API.

**Comment by astoilkov** [comment]
> With your example code I had a problem with typing the return value, the value from the hook was inferred as unknown. I ended up copying the return type into my hook and it worked (TS 3.8.3). I wonder if you need to specify the types field in package.json?

I put a "types" field into the package.json and release a new version. Can you try this again?

> One other idea for allowing extension — it might be useful to allow injecting the localStorage object into the hook (e.g. as an optional third parameter). This would allow another way to extend for SSR or for testing (with a mock localStorage), and would also allow people to inject sessionStorage, which has the same API.

I am considering it. However, I have two ideas on how those issues can be solved without modifying this library. `sessionStorage` can be made into another module as this module name is pretty descriptive and is confusing to have that functionality. The testing can be done by mocking the object globally and not by providing an option to the method. Regarding the `sessionStorage` I can create a special module for it if there is demand. For now, I have seen other people suggesting the idea but not actually needing the functionality.

**Comment by robations** [comment]
Cool, I updated and my IDE is less confused about finding the types, but I still have a problem with `unknown`.

Thinking about it, I think the problem is that when you use `ReturnType` + `typeof` there is no way to pass your type parameter to a *value* (e.g. the `useLocalStorageState` function). I did some searching and can't find a way to do this. A workaround would be to create an interface for the hook:

```ts
interface LocalStorageHook<T> {
    (key: string, defaultValue?: T): [T, Dispatch<SetStateAction<T>>];
}

// then...

export function useIsomorphicLocalStorageState<T extends {}>(
    key: string,
    defaultValue?: T,
): ReturnType<LocalStorageHook<T>> {

// Or else you need to copy the return type:

export function useIsomorphicLocalStorageState<T extends {}>(
    key: string,
    defaultValue?: T,
): [T, Dispatch<SetStateAction<T>>] {
```

> The testing can be done by mocking the object globally

IMO dependency injection > global mocking, but I will leave this to your preference. Stay safe and happy hand washing :)

**Comment by astoilkov** [comment]
Does your third option work? I like it the most.

```typescript
export function useIsomorphicLocalStorageState<T extends {}>(
    key: string,
    defaultValue?: T,
): [T, Dispatch<SetStateAction<T>>] {
```

**Comment by robations** [comment]
Yes, works for me.

(Note the `T extends {}` can be just `T` for sake of documentation — an extra constraint I needed for my project.)

**Comment by astoilkov** [comment]
Awesome. Thanks. Closing this issue for now. If you have any other suggestions or ideas please feel free to continue here or open a new issue.

Have a great day and happy hand washing :)

**Comment by astoilkov** [comment]
@robations Version 3 now supports SSR. I figured I let you know as it can be useful for you.

**Comment by robations** [comment]
Thanks for the update @astoilkov. Nothing left of my hands, by the way!
