### ISSUE TITLE
useEffect do not fire when cart state is updated

### ISSUE THREAD

**Issue by vrease** [astoilkov/use-local-storage-state#13]
FIrst. Really love `use-local-storage-state`. Good work! 💯

Issue: useEffect do not fire when cart state is updated. Any idea why?

useCart.js
```
import { createLocalStorageStateHook } from 'use-local-storage-state'

const useCart = createLocalStorageStateHook('cart', {})

export default useCart
```

cart.js (simplified)
```
import useCart from '../utils/useCart'

const [cart, setCart] = useCart()

 useEffect(() => {
        //fetch product details
    }, [cart])
```

**Comment by astoilkov** [comment]
I couldn't replicate the issue. Can you reproduce the problem in the example [here](https://codesandbox.io/s/agitated-goldstine-ypxz8?file=/src/App.js).

**Comment by vrease** [comment]
My bad! I updated state i a bad way. Works fine now! Thanks for the reply!
