### ISSUE TITLE
Calling setState with a callback as a value doesn't work

### ISSUE THREAD

**Issue by hyurl** [astoilkov/use-local-storage-state#18]
The only thing stored in the storage is `undefined`, and `setState` will not update it.

**Comment by astoilkov** [comment]
Can you give a code example?

I tried testing some scenarios but everything seems to be working fine. Also, all 29 tests pass.

**Comment by astoilkov** [comment]
I created a demo showcasing that everything works with the latest version: https://codesandbox.io/s/silent-forest-v5tot.

What version are you using?

**Comment by hyurl** [comment]
Maybe a code example is too simple that cannot test the issue. My scenario is, I used this tool in one of my component named DataForm, and my framework is based one Next.js, and this component is used in one of the page component. I don't know, possibly this module does't fit in Next.js, just like react-redux. But it should fit since I just use the following simple code in my DataForm component, which I just switched from the regular React useState:

    const [state, useState] = useLocalStorageState(location.href, {});

My goal is, to remember the state and vary by the URL, so when I jump links and come back, the history state can be reused, for example, continue editing the form that has left before.

**Comment by hyurl** [comment]
One more thing, I call setState with a function that return the new state instead of a passing the state object directly.

**Comment by astoilkov** [comment]
I successfully replicated the issue, fixed it, and released a new version.

Thank you very much! This was a big oversight on my part. I also updated the test in order to test for this in the future.

**Comment by astoilkov** [comment]
I forgot to explain the problem. Calling `setState(callback)` doesn't work. I updated the example to showcase the problem: https://codesandbox.io/s/silent-forest-v5tot.
