### ISSUE TITLE
ESM "type": "module" throwing ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by astoilkov** [astoilkov/use-local-storage-state#20]
Related comments:
- https://github.com/astoilkov/use-local-storage-state/issues/19#issuecomment-772003609
- https://github.com/astoilkov/use-local-storage-state/issues/19#issuecomment-772177934

**Comment by astoilkov** [comment]
Next.js seems to currently not support ESM modules. This is why I reverted the `"type": "module"` with [this commit](https://github.com/astoilkov/use-local-storage-state/commit/33c5730c4fdc4fbfffb95d4c85e1f739e89d72ef).

**Comment by Luccasoli** [comment]
@astoilkov now another problem has arisen :\, an image of the new error follows:

any of the dependencies / devDependencies I'm using:
    "typescript": "^4.1.3"
    "use-local-storage-state": "^8.0.0",
    "next": "10.0.6",
    "react": "17.0.1",

![image](https://user-images.githubusercontent.com/31039396/106730657-5e60f880-65ed-11eb-9b47-3d704f1fe710.png)

**Comment by astoilkov** [comment]
@Luccasoli Fixes. Sorry for the inconvenience.

**Comment by Luccasoli** [comment]
It worked, it was worth the support and congratulations for the library! :smile:

**Comment by astoilkov** [comment]
@Luccasoli Thanks!
