### ISSUE TITLE
Enhancment: use window.name as fallback

### ISSUE THREAD

**Issue by tilman** [astoilkov/use-local-storage-state#25]
Hey, just wanted to discuss the Idea of using `window.name` as a fallback instead of a global variable.

`window.name` would have the advantage of being persistent for the whole javascript session (in particular for a page reload; but not across tabs) and is still available even if cookies are turned off.

If you think that would be a better solution I would be happy to create a merge request.

Here is some more information about `window.name`:
https://www.thomasfrank.se/sessionvars.html

**Comment by astoilkov** [comment]
That's an interesting idea. I didn't know `window.name` worked like that. Can you help me by answering some questions?
- When `window.name` is lost?
  - What about the different ways to refresh the page: using the address bar, using Reload Page, using Force Reload Page?
- Is the behavior of `window.name` consistent between browsers?
- Do you know some libraries that use `window.name` for persisting data?
- Is it secure? Do iframes have access to the value?

**Comment by kolben** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Window/name

Wouldn't recommend it :smile:

**Comment by astoilkov** [comment]
@kolben I read the article. Thanks.

Why you wouldn't recommend it? What are the reasons? Thanks.

**Comment by kolben** [comment]
- The original article linked is 13 years old.
- The frameworks referenced in the mdn article are long gone and the article clearly says it shouldn't be used to store user data
- window.name will very soon [no longer be available across tabs/ windows](https://blog.mozilla.org/security/2021/04/19/firefox-88-combats-window-name-privacy-abuses/)

**Comment by astoilkov** [comment]
@kolben Yep. That's pretty definitive. Closing this issue then. Thanks!
