### ISSUE TITLE
react native support 

### ISSUE THREAD

**Issue by saleehk** [astoilkov/use-local-storage-state#27]

**Comment by astoilkov** [comment]
I don't have knowledge of React Native. Do you have ideas on what should be done to add support?

**Comment by mayank-budhiraja** [comment]
Hello @astoilkov I can assist with react-native support. Happy to help :)

**Comment by astoilkov** [comment]
@mayank-budhiraja Can you describe in a few sentences what changes are required in order to support react-native?

**Comment by mayank-budhiraja** [comment]
@astoilkov Mainly it will related to storage only. Components and Functions seems fine. Let me run an example and get back to you with approx changes.

**Comment by astoilkov** [comment]
Questions:
- Can the storage functionality will be sync? Otherwise, it would be much harder to do.
- Can the storage functionality be done without an external library? Otherwise, the package size will grow in order to support more a rare case.

**Comment by mayank-budhiraja** [comment]
@astoilkov 

- Please, check out the link to test for react-native -> https://snack.expo.io/10B7LjH3V
- I ran the tests and reached on the conclusion we need to make the environment specific or mock the browser env. 
- For example, I encountered error related to window.addEventListener
- window.addEventListener isn't provided by React Native on iOS/Android
- We will need to mock the listener like (window.addEventListener = x => x)

**Comment by astoilkov** [comment]
Thanks.

I researched this more. I think it's more appropriate to make another module that is React Native only. There are just too many things that are React Native specific. This will lead to a significant increase in complexity and bundle size.

If you are interested, you can make a fork of this repo and add support for React Native. If you support both platforms, I will add the repo in the Alternatives section in the readme. This way I will help you with the promotion.

**Comment by astoilkov** [comment]
I am closing this issue as it lacks activity.

@mayank-budhiraja If you decide to work on a react-native version, let me know so I can add it to the readme.
