### ISSUE TITLE
Unable to use with SSR via Next.js

### ISSUE THREAD

**Issue by garmeeh** [astoilkov/use-local-storage-state#3]
Trying to use this hook with Next.js and due to server side rendering it errors out on first load. 

Do you think there is a use case to check for `localStorage` and fallback to state when not available?

**Comment by garmeeh** [comment]
😬 Just seen #1, I will review that discussion and re-open if needed.

**Comment by astoilkov** [comment]
@garmeeh I am considering it. I think I will add SSR support inside the library. Either this or include a description in the readme.

**Comment by garmeeh** [comment]
Hey @astoilkov thanks for the reply. Maybe a description in the readme might be a good starting point? 

Next.js is a pretty popular framework so I could imagine it open up your library to a wider audience if it had support for SSR out of the box. If you do add support let me know, I would be happy to give it a test in Next.js and even add an example to Next.js repo.

**Comment by astoilkov** [comment]
Great, thanks. I wrote an item in my tasks to let you know.

**Comment by astoilkov** [comment]
@garmeeh Version 3 now supports SSR. You can try it out in Next.js and let me know.
