### ISSUE TITLE
[Suggestion] Add github repo link to package.json

### ISSUE THREAD

**Issue by snelsi** [astoilkov/use-local-storage-state#34]
VS Code has nice integreation with `homepage` prop defined in `package.json`. 

If `homepage` link is defined in `package.json`, it will show it on hover:

<img width="572" alt="Снимок экрана 2021-12-12 в 21 27 53" src="https://user-images.githubusercontent.com/15171036/145726602-0f9c474a-f87a-4865-9f1e-08006f403e11.png">

But sadly, this repo doesn't have a homepage link:

<img width="316" alt="Снимок экрана 2021-12-12 в 21 28 06" src="https://user-images.githubusercontent.com/15171036/145726612-7b7af800-bbbb-4b8e-bf1c-74c3b8cb9a48.png">

How about we add this info?
The following code should do the trick:
```
...
"homepage": "https://github.com/astoilkov/use-local-storage-state",
...
```

**Comment by astoilkov** [comment]
Thanks for the pull request. I am closing this issue.
