### ISSUE TITLE
Additional type exports

### ISSUE THREAD

**Issue by paulmelnikow** [astoilkov/use-local-storage-state#42]
Hi there, and thanks for this great library! Have just upgraded from v6 to v15 and it seems to be working well.

Since `createLocalStorageStateHook()` has been removed and I was using it in one place, I replaced it with my own function, which I needed to annotate with my own types. I ended up checking this in:

```ts
export type UpdateState<T> = (newValue: T | ((value: T) => T)) => void
export type LocalStorageState<T> = [T, UpdateState<T>, LocalStorageProperties]
export interface LocalStorageProperties {
  isPersistent: boolean
  removeItem: () => void
}
```

Would you consider using / exporting these types from the package? I'd be happy to open a PR.

**Comment by astoilkov** [comment]
Great idea. Thanks! I will do it, no need for a PR. I will write you when I'm done.

**Comment by astoilkov** [comment]
Done. You can see the [implementation](https://github.com/astoilkov/use-local-storage-state/commit/40a2f0ce4a569a807fc56c8239dff4a7b7ffe26e) and share your thoughts.

**Comment by paulmelnikow** [comment]
Wow, that looks great! And thanks so much! I look forward to giving it a try.

**Comment by astoilkov** [comment]
Great! I will make a new v16 release soon.
