### ISSUE TITLE
Thoughts on missing localStorage?

### ISSUE THREAD

**Issue by rexxars** [astoilkov/use-local-storage-state#5]
In certain contexts you may encounter browsers which have disabled localStorage.

If you're blocking cookies in Safari, for instance, simply trying to _access_ `localStorage` (even for a `typeof` check) will throw an error.

In other cases/browsers, attempting to actually _set_ an item will yield a quota exceeded error (they set the max quota size to 0 bytes).

An actual check for whether or not localStorage is "available and usable" would look something like:

```js
const hasLocalStorage = (() => {
  try {
      if (typeof localStorage === 'undefined') {
          return false
      }

      // Can we actually use it? "quota exceeded" errors in Safari, etc
      const mod = '__lscheck'
      localStorage.setItem(mod, mod)
      localStorage.removeItem(mod)
  } catch (err) {
      return false
  }

  return true
})()
```

Even with such a check, the "solution" isn't obvious - what should a library such as this one _do_ in this case? Throw? Warn? Pretend like it isn't happening?

Given that you often use this as a "drop-in" replacement for `setState`, I would at least expect it to fall back to using in-memory state - but in that case, how far do you go? Try to implement postMessage calls for cross-tab/window polyfilling of the missing `storage` events? 

I'm raising this mostly to get your perspective, but I also feel that perhaps we should try to implement something that prevents this hook from potentially blocking the page from being rendered should the user have disabled localStorage.

**Comment by astoilkov** [comment]
Respect for the type of issue you have created. This is what I call a way to approach problems – with questions.

These aren't easy questions. Can you give me a few days to think about it and we can discuss them after that?

**Comment by astoilkov** [comment]
I saw that type of thinking in your post: https://espen.codes/post/strictness-in-apis-or-why-hapi-rocks. Nice!

**Comment by astoilkov** [comment]
```typescript
const [value, setValue, isPersistent] = useLocalStorageState('key')
```

What do you think about such an API? The hook will return an additional boolean to let you know if the data is currently being persisted in localStorage or not?

**Comment by rexxars** [comment]
I like it! Leave it up to the app developer whether or not they care :)

**Comment by astoilkov** [comment]
I am done with the implementation. Can you check it out and tell me what you think?

**Comment by rexxars** [comment]
This looks great!

**Comment by astoilkov** [comment]
Perfect. I am closing this issue then. If you have more valuable feedback please don't hesitate to write it.
