### ISSUE TITLE
need guidance for using sessionStorage also

### ISSUE THREAD

**Issue by rhythmbhiwani** [astoilkov/use-local-storage-state#51]
For some of my usecase, I also need support for using sessionStorage also, but this library seems to focus only only on local-storage. Can you please guide me how can I convert it to use both local and session storage based on some parameters. I can fork the repo and change it in that repo, so that this library can focus on local storage

**Comment by astoilkov** [comment]
I'm working on a branch, that's mostly done, that will allow specifying a `storage` option. You can then pass `sessionStorage` to the option. You can take a look at it here: https://github.com/astoilkov/use-local-storage-state/tree/storage-option#optionsstorage.

**Comment by astoilkov** [comment]
I will soon post a solution for this. Thanks for the patience.
