### ISSUE TITLE
Latest version on npm is 17.3.0, rather than 18.2.0

### ISSUE THREAD

**Issue by dumbmatter** [astoilkov/use-local-storage-state#58]
https://www.npmjs.com/package/use-local-storage-state?activeTab=versions

**Comment by astoilkov** [comment]
Many thanks. Do you know of a way to make the 18.2.0 latest without publishing a new 18.2.1 release?

**Comment by dumbmatter** [comment]
I'm not sure, sorry.

**Comment by astoilkov** [comment]
No worries. I've just published a patch to make it the latest.

Thanks for notifying me!
