### ISSUE TITLE
useEffect run on every render

### ISSUE THREAD

**Issue by cdock1029** [astoilkov/use-local-storage-state#6]
Is it necessary that you are not providing at least an empty dependency array here
https://github.com/astoilkov/use-local-storage-state/blob/d84473109493f120d342f275c925d69566a1b661/index.ts#L103

meaning this runs on every render (which [can be many many times](https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects) in concurrent mode)?

**Comment by astoilkov** [comment]
It seems I overlooked this. I fixed it. Thanks!
