### ISSUE TITLE
block all cookies in safari breaks the hook

### ISSUE THREAD

**Issue by bobaaaaa** [astoilkov/use-local-storage-state#62]
If you "block cookies" in safari, this hooks throws uncatched errors. It is not enough to surround the `localStorage.getItem()` call in a try-catch block. Even the `localStorage` access throws:

<img width="316" alt="Bildschirmfoto 2023-05-10 um 13 56 24" src="https://github.com/astoilkov/use-local-storage-state/assets/733158/812b03ff-2792-4f71-bfd0-bd4f92fe6691">

This happened also for https://github.com/astoilkov/use-session-storage-state

Safari (16.4) settings promt. (sorry for the german language) 

<img width="805" alt="safari" src="https://github.com/astoilkov/use-local-storage-state/assets/733158/5cf7ef0c-1d30-4356-811b-cc010b408947">

**Comment by astoilkov** [comment]
I will fix this soon. Thanks!

**Comment by astoilkov** [comment]
This is now part of the latest release. Again, thanks for reporting!

**Comment by bobaaaaa** [comment]
Thank you. It works 👍. Will wait for `use-session-storage-state` because we are using both libs

**Comment by bobaaaaa** [comment]
@astoilkov should I create an issue on the https://github.com/astoilkov/use-session-storage-state repo?

**Comment by astoilkov** [comment]
Yeah, would probably be easier for you to keep track. Here I've done it: https://github.com/astoilkov/use-session-storage-state/issues/2.

Out of curiosity, where are you using both libraries?

**Comment by bobaaaaa** [comment]
My team is building [t-online.de](https://www.t-online.de). It is one of the biggest german (online) news portals (300mio visits/month)

**Comment by astoilkov** [comment]
Wow. Is your organization open to sponsoring my work?

I'm not sure if you are familiar with the situation in open-source. It's the work of a lot of people that get little credit and money for the work they do. I think big organizations like yours are a way to improve that situation. This is a growing problem and the open-source community is trying to find a solution. This is why I'm experimenting with asking (inspiration: https://reactflow.dev/blog/asking-for-money-for-open-source/).

Thanks.

**Comment by bobaaaaa** [comment]
Sure. I will ask my boss.

**Comment by astoilkov** [comment]
Thank you!
