### ISSUE TITLE
Migrating from `createLocalStorageStateHook`

### ISSUE THREAD

**Issue by FarazPatankar** [astoilkov/use-local-storage-state#64]
Hey, so I am seeing a few usages of `createLocalStorageStateHook` in our codebase and I noticed the latest version does not have this function?

I also went through the releases and didn't see a mention of it being removed as a breaking change. Could I get any pointers on how to migrate the existing usages?

**Comment by FarazPatankar** [comment]
I think I figured it out. Basically went from:
```ts
export const useParticles = createLocalStorageStateHook(
  "@railway/particles",
  false,
);

const [showParticles, setShowParticles] = useParticles();
```

to:
```ts
export const useParticles = () =>
  useLocalStorageState("@railway/particles", {
    defaultValue: false,
  });
  
// Usage remains the same
const [showParticles, setShowParticles] = useParticles();
```
  
Leaving it open so you can correct me if I am wrong. 😄

**Comment by FarazPatankar** [comment]
Everything else seems fine, we use the lib pretty heavily, great work! 💚

**Comment by astoilkov** [comment]
- [x] warm feeling generated
