### ISSUE TITLE
Compiler target causing error in Edge (non-Chromium)

### ISSUE THREAD

**Issue by willviles** [astoilkov/use-local-storage-state#7]
Targeting ES2019 in your tsconfig.json compiler options causes problems when bundled into sites running Edge (non-Chromium). 

This is because Edge still doesn't handle [optional catch binding](https://mariusschulz.com/blog/optional-catch-binding-in-typescript) properly.

```js
} catch { // syntax error

} catch (err) { // fine
```

Simply changing the compiler target from `ES2019` to `ES5` or `ES6` should solve this.

https://github.com/astoilkov/use-local-storage-state/blob/647cbb78536055d8af5b735d47eaa6eb736a9dc9/tsconfig.json#L4

**Comment by astoilkov** [comment]
Makes sense. I will do it. Thanks!

**Comment by astoilkov** [comment]
Sorry for the slow response.

I made the change and published a new release.

**Comment by willviles** [comment]
Thanks!
