### ISSUE TITLE
Set value not persisting as expected

### ISSUE THREAD

**Issue by mjp0** [astoilkov/use-local-storage-state#78]
I'm using this library to hold a version history for a document. It's as simple as it gets: it's an array where every saved version is being appended to. However, the array gets stuck. With new doc, it saves one item and then on subsequent times, no matter how many times I save, `versionHistory` array contains only that one item plus the latest saved. All the intermediate saves don't exist. In other words, `setVersionHistory` executes but changes are not persisted in `versionHistory` beyond that initial item. But, if I reload the page, now `versionHistory` contains the first and second item, and the same thing happens with the third element. So, basically, `versionHistory` is not being updated as expected.

This component is also fully on the client-side, so ssr shouldn't be messing things up. Any ideas what might be going wrong?
<img width="394" alt="image" src="https://github.com/user-attachments/assets/0420ab16-1e7b-4ad3-aa55-efcac016962e" />
Here, each item inside the arrays within `versionHistory` is a save (I'm just adding a line for each save to test), so as you can see, saves for lines 1, 2, 3 and 5, 6 just went poof. The reason why 7 and 8 are persisted is that I reloaded the page.  
<img width="310" alt="image" src="https://github.com/user-attachments/assets/0ae638ab-3692-4de5-ab11-43e62e1ddc4f" />

**Comment by astoilkov** [comment]
Hmm, this looks strange. However, I can't guess what might be the reason for this. This hook is used quite a lot and I guess it shouldn't be something obvious.

Do you think you can make an isolated CodeSandbox example replicating the issue? This way I can debug and figure out what's going on.

**Comment by mjp0** [comment]
I finally had time to debug this further and I think this was React being React again. I refactored this into a separate component and now it's working as expected. The previous component probably has one too many states and since React's state system is a house of cards, I guess I put one too many cards on the stack 🤷‍♂️
