### ISSUE TITLE
Add support to removeItem

### ISSUE THREAD

**Issue by fsmaia** [astoilkov/use-local-storage-state#8]
How about adding a third item in the tuple that invokes `.removeItem`, and then being able to clean the entry? In cases where `undefined` is the initial value, this is commonly desirable IMHO.

I may add a PR if you will :)

**Comment by astoilkov** [comment]
Why not just execute `setState(undefined)`?

**Comment by fsmaia** [comment]
Actually, in my scenario, there are two provider components, each one using a `createLocalStorageStateHook` under different keys. When calling the inner provider's `setState`, it is invoking the outer one. I'm trying hard to investigate what's happening and I'll start another issue when I figure it out.

In a simpler test, your suggestion works just fine, and this issue may be closed since, IMHO, it's way better to do this than exposing another tuple item to the hook.

**Comment by astoilkov** [comment]
> Actually, in my scenario, there are two provider components, each one using a createLocalStorageStateHook under different keys. When calling the inner provider's setState, it is invoking the outer one. I'm trying hard to investigate what's happening and I'll start another issue when I figure it out.

This is interesting. Let me know if you discover something.

> In a simpler test, your suggestion works just fine, and this issue may be closed since, IMHO, it's way better to do this than exposing another tuple item to the hook.

Perfect, I am closing this issue.

**Comment by katelovescode** [comment]
When I tried this, it sets my value to the string "undefined" rather than removing it.  Ditto for "null".  I can do a string comparison but that's not really what I would expect.  Can we reopen this issue?

**Comment by astoilkov** [comment]
@katelovescode Will find a solution soon.

**Comment by astoilkov** [comment]
@katelovescode What do you think about a `reset()` function available on the `setState` value like this:
```typescript
const [todos, setTodos] = useLocalStorageState('todos', ['first', 'second'])

function onClick() {
  setTodos.reset()
}
```

**Comment by katelovescode** [comment]
> @katelovescode What do you think about a `reset()` function available on the `setState` value like this:
> 
> ```ts
> const [todos, setTodos] = useLocalStorageState('todos', ['first', 'second'])
> 
> function onClick() {
>   setTodos.reset()
> }
> ```

Could you pass it a key to remove only that key?  Or will this reset all of the localstorage state you've set?

**Comment by astoilkov** [comment]
What do you mean by "all of the localstorage state"?

The `reset()` call will clear only one key – `todos`. Everything else in the localStorage will be untouched.

**Comment by katelovescode** [comment]
Oh!  I get it, sorry, I misunderstood.  Yes, this sounds great!

**Comment by astoilkov** [comment]
This is now implemented. I am closing this issue. Thanks for the help!
