### ISSUE TITLE
Session Storage support?

### ISSUE THREAD

**Issue by natac13** [astoilkov/use-local-storage-state#9]
Is there any plans to let the user choose between localstorage and session storage. Or even between using the default value over the stored value?

I have a use case that I would only like to use the stored value during the same user session.

**Comment by astoilkov** [comment]
> Is there any plans to let the user choose between localstorage and session storage.

I am considering supporting session storage. I am not sure about it yet.

> Or even between using the default value over the stored value?

Can you clarify on that? I'm not sure I understand it correctly.

**Comment by natac13** [comment]
> Is it possible that you share your use case? I am interested in why keeping it in memory doesn't work for you.

Maybe using memory is the answer for me. 

> Can you clarify on that? I'm not sure I understand it correctly.

The use case is a landing page with full page sections, on scroll I set a page number from `useState`. The full page section then changes. Upon clicking a nav link and then using the back button I would like the user to be on the same full page section of the landing page. However when they close the tab or navigate directly to the home page via url I would like to show the `0` full page section.

**Comment by astoilkov** [comment]
Yes, it seems you can do this without session storage.

I am closing this issue. If I have misunderstood something please feel free to write back.

**Comment by Taraluktus** [comment]
One advantage for sessionStorage over in-memory is, that it survives page reload, and it behaves at tab clone/duplicate as a user would expect it.
localStorage could do that too, but it's a bit too "persistent" for our use case.

**Comment by astoilkov** [comment]
@Taraluktus Are you teammates with @natac13? I am asking because the use case @natac13 described can be done with [hash URLs](https://developer.mozilla.org/en-US/docs/Web/API/URL/hash). This way the position of the section will be remembered on page reload and tab duplication.

**Comment by Taraluktus** [comment]
No, totally unrelated to him.
We only use localStorage/sessionStorage for the JWT token.

**Comment by astoilkov** [comment]
@Taraluktus Do you use any kind of abstraction for the session storage?

**Comment by Taraluktus** [comment]
No, before useLocalStorageState, we used sessionStorage directly.

**Comment by astoilkov** [comment]
@Taraluktus How did you swap using sessionStorage with using localStorage? Isn't sessionStorage the thing you need?

**Comment by Taraluktus** [comment]
They work nearly the same, and also have the same API (but I think you already knew that).
We wanted to use a hook-based solution, and this one is the most mature. Nevermind, we are now taking a custom approach since the use case is very specific. (can be closed)

**Comment by astoilkov** [comment]
@Taraluktus Thank you for the time taken to answer my questions. This has been very useful. I will leave the implementation of sessionStorage for now and wait for more feedback.

**Comment by Taraluktus** [comment]
Fair enough.
There is another caveat: the storage DOM event is not fired for sessionStorage, which makes it hard to track changes. A one-to-one implementation (replacing localStorage with sessionStorage) would not work as expected.

**Comment by astoilkov** [comment]
Hi all,

For people interested, I've published a [`use-session-storage-state`](https://www.npmjs.com/package/use-session-storage-state) package. The repo — https://github.com/astoilkov/use-session-storage-state.
